on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      # Make Repo name lowercase for Docker
      - id: repo
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{github.repository}}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      # Create tag
      - name: Create tag
        id: tagger
        uses: phish108/autotag-action@1.1.52
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}

      # Setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # Login to Github Container Registry
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build Docker Image
      - name: Build Docker Image and push to Github Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ steps.repo.outputs.lowercase }}:${{ steps.branch-name.outputs.current_branch }}
            ghcr.io/${{ steps.repo.outputs.lowercase }}:latest
            ghcr.io/${{ steps.repo.outputs.lowercase }}:${{ steps.branch-name.outputs.current_branch }}-${{ steps.tagger.outputs.new-tag }}
          # Only push to Docker Hub if on main branch or staging branch
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=${{ steps.repo.outputs.lowercase }}:latest
          cache-to: type=inline
          secrets: |
            "SENTRY_TOKEN=${{ secrets.SENTRY_TOKEN }}"
